[15/08/2016 01:13] ERROR red load_cogs 348: imgurpython is not installed. Do 'pip3 install imgurpython' to use this cog.
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\image.py", line 108, in setup
    from imgurpython import ImgurClient
ImportError: No module named 'imgurpython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 345, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 532, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 719, in load_extension
    lib.setup(self)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\image.py", line 110, in setup
    raise ModuleNotFound("imgurpython is not installed. Do 'pip3 install imgurpython' to use this cog.")
cogs.image.ModuleNotFound: imgurpython is not installed. Do 'pip3 install imgurpython' to use this cog.
[15/08/2016 01:40] ERROR owner load 68: ('named arguments must follow bare *', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\general.py', 122, 26, 'async def _jerm(self, *):\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 531, in _load_cog
    importlib.reload(mod_obj)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\general.py", line 122
    async def _jerm(self, *):
                            ^
SyntaxError: named arguments must follow bare *

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('named arguments must follow bare *', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\general.py', 122, 26, 'async def _jerm(self, *):\n'))
[15/08/2016 01:40] ERROR owner load 68: ('named arguments must follow bare *', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\general.py', 122, 26, 'async def _jerm(self, *):\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 531, in _load_cog
    importlib.reload(mod_obj)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 626, in _exec
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\general.py", line 122
    async def _jerm(self, *):
                            ^
SyntaxError: named arguments must follow bare *

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('named arguments must follow bare *', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\general.py', 122, 26, 'async def _jerm(self, *):\n'))
[15/08/2016 01:50] ERROR owner load 68: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 10, 25, '    async def jerm(self)\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 10
    async def jerm(self)
                       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 10, 25, '    async def jerm(self)\n'))
[15/08/2016 01:51] ERROR owner load 68: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 11, 25, '    async def jerm(self)\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 11
    async def jerm(self)
                       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 11, 25, '    async def jerm(self)\n'))
[15/08/2016 01:52] ERROR owner load 68: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 10, 26, '    async def jerms(self)\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 10
    async def jerms(self)
                        ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 10, 26, '    async def jerms(self)\n'))
[15/08/2016 01:54] ERROR owner load 68: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 10, 25, '    async def Jerm(self)\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 10
    async def Jerm(self)
                       ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 64, in load
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 10, 25, '    async def Jerm(self)\n'))
[15/08/2016 02:44] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 21, 35, '    async def superTriggered(self)\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 21
    async def superTriggered(self)
                                 ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 21, 35, '    async def superTriggered(self)\n'))
[15/08/2016 02:45] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 21, 35, '    async def superTriggered(self)\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 21
    async def superTriggered(self)
                                 ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 21, 35, '    async def superTriggered(self)\n'))
[15/08/2016 02:45] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 21, 35, '    async def supertriggered(self)\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 21
    async def supertriggered(self)
                                 ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 21, 35, '    async def supertriggered(self)\n'))
[15/08/2016 02:47] ERROR red on_command_error 88: Exception in command 'superTriggered'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 23, in superTriggered
    self.bot.triggered()
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 264, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'triggered'
[15/08/2016 02:48] ERROR red on_command_error 88: Exception in command 'superTriggered'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 23, in superTriggered
    self.bot.triggered(self)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 264, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'triggered'
[15/08/2016 02:49] ERROR red on_command_error 88: Exception in command 'superTriggered'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 23, in superTriggered
    triggered(self)
NameError: name 'triggered' is not defined
[15/08/2016 02:49] ERROR red on_command_error 88: Exception in command 'superTriggered'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 23, in superTriggered
    self.triggered(self)
TypeError: 'Command' object is not callable
[15/08/2016 02:50] ERROR red on_command_error 88: Exception in command 'superTriggered'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 23, in superTriggered
    await self.triggered(self)
TypeError: 'Command' object is not callable
[15/08/2016 02:50] ERROR red on_command_error 88: Exception in command 'superTriggered'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 23, in superTriggered
    await self.bot.say(self.triggered(self))
TypeError: 'Command' object is not callable
[15/08/2016 02:57] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 24, 29, '    async def fuckYeah(self)\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 24
    async def fuckYeah(self)
                           ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 24, 29, '    async def fuckYeah(self)\n'))
[15/08/2016 03:03] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("─────────────────────────▄▀▄\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 32
    await.self.bot.say("─────────────────────────▄▀▄
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("─────────────────────────▄▀▄\n'))
[15/08/2016 03:04] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say(""─────────────────────────▄▀▄\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 32
    await.self.bot.say(""─────────────────────────▄▀▄
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say(""─────────────────────────▄▀▄\n'))
[15/08/2016 03:07] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("─────────────────────────▄▀▄─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─▀█▀█▄─────────────────────────█──█──█─────────────────────────█▄▄█──▀█────────────────────────▄█──▄█▄─▀█────────────────────────█─▄█─█─█─█────────────────────────█──█─█─█─█────────────────────────█──█─█─█─█────▄█▄──▄█▄────────────█──▀▀█─█─█──▄█████████────────────▀█───█─█▄▀─▄███████████────────────██──▀▀─█▄█████████████────────────█─────███████████───▀▀█▄─────────▀█────█████████───▀▀▀──█──────────█────███████───────██─▀█─────────█────█████──▄──────────▀█────────█────█ Look son!███──█──────▀▀█───▀█───────█────█ A Retard!███─▀─██──────█────▀█──────█──███─────────────────▀█─────█────████──────────────────█─────█────████─────────────▄▀───█─────█────█████─────────▄▄██────█▄────█────█████────────██████────█────█────██████────█──███████▀──█───▄█▄▄▄▄███▀▀██────▀─██▄──▄█───█───█─────███▄──────────██████───█───█─────█─██▄────────────▄▄────█───█─────█─███████─────────────▄█───█─────█──██████─────────────█───█▀─────█──▄███████▄─────────▄█──█▀──────█─▄█─────▄▀▀▀█───────█───█───────█▄█────────█──█────▄███▀▀▀▀──────██──▄▀▀────────█──▄▀──█──────────██────█─────────█─────█──────────██────────▀█────█─────█─────────███───────────────█──▄█▀────────█──────────██───█▀▀▀───────────██───────────────█──────────────██▄─────────────██──────────────█─█▄────────────█───────────────█──██▄────────▄███▀▀▀▀▀▄────────█─█▀─▀█▄────────▀█──────▀▄───────█────▀▀▀▀▄─────█────────▀─────█─█─────────▀▄──▀───────────────█")\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 32
    await.self.bot.say("─────────────────────────▄▀▄─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─▀█▀█▄─────────────────────────█──█──█─────────────────────────█▄▄█──▀█────────────────────────▄█──▄█▄─▀█────────────────────────█─▄█─█─█─█────────────────────────█──█─█─█─█────────────────────────█──█─█─█─█────▄█▄──▄█▄────────────█──▀▀█─█─█──▄█████████────────────▀█───█─█▄▀─▄███████████────────────██──▀▀─█▄█████████████────────────█─────███████████───▀▀█▄─────────▀█────█████████───▀▀▀──█──────────█────███████───────██─▀█─────────█────█████──▄──────────▀█────────█────█ Look son!███──█──────▀▀█───▀█───────█────█ A Retard!███─▀─██──────█────▀█──────█──███─────────────────▀█─────█────████──────────────────█─────█────████─────────────▄▀───█─────█────█████─────────▄▄██────█▄────█────█████────────██████────█────█────██████────█──███████▀──█───▄█▄▄▄▄███▀▀██────▀─██▄──▄█───█───█─────███▄──────────██████───█───█─────█─██▄────────────▄▄────█───█─────█─███████─────────────▄█───█─────█──██████─────────────█───█▀─────█──▄███████▄─────────▄█──█▀──────█─▄█─────▄▀▀▀█───────█───█───────█▄█────────█──█────▄███▀▀▀▀──────██──▄▀▀────────█──▄▀──█──────────██────█─────────█─────█──────────██────────▀█────█─────█─────────███───────────────█──▄█▀────────█──────────██───█▀▀▀───────────██───────────────█──────────────██▄─────────────██──────────────█─█▄────────────█───────────────█──██▄────────▄███▀▀▀▀▀▄────────█─█▀─▀█▄────────▀█──────▀▄───────█────▀▀▀▀▄─────█────────▀─────█─█─────────▀▄──▀───────────────█")
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("─────────────────────────▄▀▄─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─█─────────────────────────█─▀█▀█▄─────────────────────────█──█──█─────────────────────────█▄▄█──▀█────────────────────────▄█──▄█▄─▀█────────────────────────█─▄█─█─█─█────────────────────────█──█─█─█─█────────────────────────█──█─█─█─█────▄█▄──▄█▄────────────█──▀▀█─█─█──▄█████████────────────▀█───█─█▄▀─▄███████████────────────██──▀▀─█▄█████████████────────────█─────███████████───▀▀█▄─────────▀█────█████████───▀▀▀──█──────────█────███████───────██─▀█─────────█────█████──▄──────────▀█────────█────█ Look son!███──█──────▀▀█───▀█───────█────█ A Retard!███─▀─██──────█────▀█──────█──███─────────────────▀█─────█────████──────────────────█─────█────████─────────────▄▀───█─────█────█████─────────▄▄██────█▄────█────█████────────██████────█────█────██████────█──███████▀──█───▄█▄▄▄▄███▀▀██────▀─██▄──▄█───█───█─────███▄──────────██████───█───█─────█─██▄────────────▄▄────█───█─────█─███████─────────────▄█───█─────█──██████─────────────█───█▀─────█──▄███████▄─────────▄█──█▀──────█─▄█─────▄▀▀▀█───────█───█───────█▄█────────█──█────▄███▀▀▀▀──────██──▄▀▀────────█──▄▀──█──────────██────█─────────█─────█──────────██────────▀█────█─────█─────────███───────────────█──▄█▀────────█──────────██───█▀▀▀───────────██───────────────█──────────────██▄─────────────██──────────────█─█▄────────────█───────────────█──██▄────────▄███▀▀▀▀▀▄────────█─█▀─▀█▄────────▀█──────▀▄───────█────▀▀▀▀▄─────█────────▀─────█─█─────────▀▄──▀───────────────█")\n'))
[15/08/2016 03:12] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("╭━━━━━━━╮ \\\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 32
    await.self.bot.say("╭━━━━━━━╮ \
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("╭━━━━━━━╮ \\\n'))
[15/08/2016 03:13] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 31, 15, '    async def (self):\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 31
    async def (self):
              ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 31, 15, '    async def (self):\n'))
[15/08/2016 03:13] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("╭━━━━━━━╮ \\n┃\u3000\u3000● ══\u3000 █ ┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃█ ur adopted. █┃ \\n┃█ -Mom&Dad █┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃\u3000\u3000\u3000○\u3000\u3000\u3000 ┃ \\n╰━━━━━━━╯"\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 32
    await.self.bot.say("╭━━━━━━━╮ \n┃　　● ══　 █ ┃ \n┃██████████┃ \n┃██████████┃ \n┃██████████┃ \n┃█ ur adopted. █┃ \n┃█ -Mom&Dad █┃ \n┃██████████┃ \n┃██████████┃ \n┃██████████┃ \n┃　　　○　　　 ┃ \n╰━━━━━━━╯"
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("╭━━━━━━━╮ \\n┃\u3000\u3000● ══\u3000 █ ┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃█ ur adopted. █┃ \\n┃█ -Mom&Dad █┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃\u3000\u3000\u3000○\u3000\u3000\u3000 ┃ \\n╰━━━━━━━╯"\n'))
[15/08/2016 03:14] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("╭━━━━━━━╮ \\n┃\u3000\u3000● ══\u3000 █ ┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃█ ur adopted. █┃ \\n┃█ -Mom&Dad █┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃\u3000\u3000\u3000○\u3000\u3000\u3000 ┃ \\n╰━━━━━━━╯")\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 32
    await.self.bot.say("╭━━━━━━━╮ \n┃　　● ══　 █ ┃ \n┃██████████┃ \n┃██████████┃ \n┃██████████┃ \n┃█ ur adopted. █┃ \n┃█ -Mom&Dad █┃ \n┃██████████┃ \n┃██████████┃ \n┃██████████┃ \n┃　　　○　　　 ┃ \n╰━━━━━━━╯")
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 32, 14, '        await.self.bot.say("╭━━━━━━━╮ \\n┃\u3000\u3000● ══\u3000 █ ┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃█ ur adopted. █┃ \\n┃█ -Mom&Dad █┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃██████████┃ \\n┃\u3000\u3000\u3000○\u3000\u3000\u3000 ┃ \\n╰━━━━━━━╯")\n'))
[15/08/2016 03:20] ERROR owner _reload 154: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 21, 9, '    async def triggered(self):\n'))
Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 530, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 21
    async def triggered(self):
        ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 148, in _reload
    self._load_cog(module)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\owner.py", line 534, in _load_cog
    raise CogLoadError(*e.args)
cogs.owner.CogLoadError: ('invalid syntax', ('C:\\Users\\Jackson\\Desktop\\SoulBot\\Red-DiscordBot\\cogs\\test.py', 21, 9, '    async def triggered(self):\n'))
[15/08/2016 03:31] ERROR red on_command_error 88: Exception in command 'lookSon'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 92, in lookSon
    await self.bot.say(self.adoptedLines[x])
IndexError: list index out of range
[15/08/2016 03:32] ERROR red on_command_error 88: Exception in command 'lookSon'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 92, in lookSon
    await self.bot.say(self.lookSonLines[x])
IndexError: list index out of range
[15/08/2016 03:33] ERROR red on_command_error 88: Exception in command 'lookSon'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 92, in lookSon
    await self.bot.say(self.lookSonLines[x])
IndexError: list index out of range
[15/08/2016 03:34] ERROR red on_command_error 88: Exception in command 'lookSon'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 92, in lookSon
    await self.bot.say(self.lookSonLines[x])
IndexError: list index out of range
[15/08/2016 04:01] ERROR red on_command_error 88: Exception in command 'noticeMe'
Traceback (most recent call last):
  File "C:\Users\Jackson\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Jackson\Desktop\SoulBot\Red-DiscordBot\cogs\test.py", line 98, in noticeMe
    await self.bot.say("Notice me " + user + " !")
TypeError: Can't convert 'Member' object to str implicitly
